server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  application:
    name: mcp-client
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
    vectorstore:
      redis:
        enabled: true
        initialize-schema: true  #是否初始化所需模式
        index-name: lee-vectorstore #用于存储向量的名称
        prefix: 'embedding:'  # redis键的前缀
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000
      connect-timeout: 2000
      database: 0
logging:
  level:
    ai:
      djl: debug
internet:
  websearch:
    searxng:
      url: http://127.0.0.1:8888/search
      limit: 10