server:
  port: 8081

spring:
  application:
    name: mcp-client
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
    vectorstore:
      redis:
        initialize-schema: true  #是否初始化所需模式
        index-name: lee-vectorstore #用于存储向量的名称
        prefix: 'embedding:'  # redis键的前缀
  data:
    redis:
      host: 127.0.0.1
      port: 6379
